server:
  port: 8800

mybatis-plus:
  mapper-locations: classpath*:com/next/jiangzh/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true


spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/woaijiadanoo/springconfig.git
          username: woaijiadanoo
          password: jiangzh_next@123
          repos:
            zuulService:
              pattern: zuulService/**
              uri: https://github.com/woaijiadanoo/next_zuul.git
          basedir: ./nextfilm_config_server/gitdata
          clone-on-start: true
  application:
    name: config-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/next_springcloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml


