server:
  port: 8701

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    cinema:
      path: /cinemaapi/**
      serviceId: cinemaService
    order:
      path: /orderapi/**
      serviceId: orderService

mybatis-plus:
  mapper-locations: classpath*:com/next/jiangzh/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  application:
    name: zuulService
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/next_springcloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml

